# Generated by Django 5.0.6 on 2024-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_category_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoutcome',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productoutcome',
            name='design_efforts',
        ),
        migrations.RemoveField(
            model_name='value',
            name='company',
        ),
        migrations.RemoveField(
            model_name='value',
            name='design_efforts',
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('OBJ', 'Objective'), ('VAL', 'Value'), ('OUT', 'Outcome')], max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.company')),
                ('design_efforts', models.ManyToManyField(blank=True, to='portal.designeffort')),
            ],
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.DeleteModel(
            name='ProductOutcome',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
