# Generated by Django 5.0.6 on 2024-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to='images/company-logos/'),
        ),
    ]
