# Generated by Django 5.0.6 on 2024-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_project_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='local_id',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
