# Generated by Django 5.0.6 on 2024-06-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_purpose_local_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.PositiveIntegerField(editable=False)),
                ('design_effort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.designeffort')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.mapping')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEffortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('project_effort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portal.projecteffort')),
            ],
        ),
    ]
