# Generated by Django 5.0.6 on 2024-05-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_invitation_rejected_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile-pics/'),
        ),
    ]
