# Generated by Django 5.0.6 on 2024-06-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_projecteffort_created_at_projecteffort_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecteffort',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecteffort',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_project_efforts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecteffort',
            name='value_status',
            field=models.CharField(choices=[('YBC', 'Yet to be checked'), ('UCH', 'Unchecked'), ('UPA', 'Unplanned Activity'), ('REA', 'Realised'), ('VUR', 'Value Unrealised')], default='YBC', max_length=3),
        ),
        migrations.AlterField(
            model_name='projecteffort',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_efforts', to=settings.AUTH_USER_MODEL),
        ),
    ]
