# Generated by Django 5.0.6 on 2024-05-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'company')},
        ),
    ]
